const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.video,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.video.Cnds.PickByUID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.video.Cnds.OnPlaybackEvent,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{videoIndex: 0},
	{Video1: 0},
	{videoUID: 0},
	{kulp: 0},
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{Video2: 0},
	{Video3: 0},
	{Video4: 0},
	{Video5: 0},
	{Video6: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{bg: 0},
	{Genel: 0},
	{sagBand: 0},
	{solBand: 0},
	{şeritler: 0},
	{masa: 0},
	{isClicked: 0},
	{tanecikBtn: 0},
	{gasBtn: 0},
	{solKulp: 0},
	{sagKulp: 0},
	{isActive: 0},
	{nextBtn: 0},
	{prevBtn: 0},
	{Video7: 0},
	{Video8: 0},
	{kulps: 0},
	{videos: 0},
	{showKulpOutline: 0},
	{showBtnOutline: 0},
	{gasMode: 0},
	{videoModeComplete: 0},
	{videoUIDArray: 0},
	{activeItemIndex: 0},
	{LevelEndControl: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Video1: class extends self.IWorldInstance {},
	kulp: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Video3: class extends self.IWorldInstance {},
	Video4: class extends self.IWorldInstance {},
	Video5: class extends self.IWorldInstance {},
	Video6: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Genel: class extends self.ISpriteInstance {},
	sagBand: class extends self.ISpriteInstance {},
	solBand: class extends self.ISpriteInstance {},
	şeritler: class extends self.ISpriteInstance {},
	masa: class extends self.ISpriteInstance {},
	tanecikBtn: class extends self.ISpriteInstance {},
	gasBtn: class extends self.ISpriteInstance {},
	solKulp: class extends self.ISpriteInstance {},
	sagKulp: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	prevBtn: class extends self.ISpriteInstance {},
	Video7: class extends self.IWorldInstance {},
	Video8: class extends self.IWorldInstance {},
	kulps: class extends self.ISpriteInstance {},
	videos: class extends self.IWorldInstance {}
}